services:
  db:
    image: oscarfonts/h2
    environment:
      - H2_OPTIONS=-ifNotExists
    ports:
      - "8082:8082"

  app:
    image: nameimage
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://db:1521/mydatabase
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password